name: build

on:
  push:
  pull_request:

# TODO: Check different standards?

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        compiler: [g++-10, clang++-14]
        target: [Debug, Release]
    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: sudo apt install gcc-10 g++-10 libgcc-10-dev
    - name: build
      run: |
           mkdir -p build
           cd build
           cmake .. \
            -DCMAKE_BUILD_TYPE=${{matrix.target}} \
            -DCMAKE_CXX_COMPILER=${{matrix.compiler}} \
            -DCPPTRACE_BACKTRACE_PATH=/usr/lib/gcc/x86_64-linux-gnu/11/include/backtrace.h \
            -DASSERT_BUILD_BASIC_TEST=On
           make -j
  build-macos:
    runs-on: macos-13
    strategy:
      fail-fast: false
      matrix:
        compiler: [g++-13, clang++]
        target: [Debug, Release]
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
           mkdir -p build
           cd build
           cmake .. \
            -DCMAKE_BUILD_TYPE=${{matrix.target}} \
            -DCMAKE_CXX_COMPILER=${{matrix.compiler}} \
            -DASSERT_BUILD_BASIC_TEST=On
           make -j
  build-windows:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        compiler: [cl, clang++]
        target: [Debug, Release]
    steps:
    - uses: actions/checkout@v2
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.10.0
    - name: build
      run: |
           mkdir -p build
           cd build
           cmake .. `
            -DCMAKE_BUILD_TYPE=${{matrix.target}} `
            -DCMAKE_CXX_COMPILER=${{matrix.compiler}} `
            -DASSERT_BUILD_BASIC_TEST=On
           msbuild .\libassert.sln
  build-mingw:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        compiler: [g++]
        target: [Debug, Release]
    steps:
    - uses: actions/checkout@v2
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.10.0
    - name: build
      run: |
           mkdir -p build
           cd build
           cmake .. `
            -DCMAKE_BUILD_TYPE=${{matrix.target}} `
            -DCMAKE_CXX_COMPILER=${{matrix.compiler}} `
            -DASSERT_BUILD_BASIC_TEST=On `
            "-GUnix Makefiles"
           make -j
