name: build

on:
  push:
  pull_request:

# TODO: Check different standards?

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        compiler: [g++-10, clang++-14]
        cxx-version: [17, 20]
        target: [Debug, Release]
    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: sudo apt install gcc-10 g++-10 libgcc-10-dev
    - name: build
      run: |
           mkdir -p build
           cd build
           cmake .. \
            -DCMAKE_BUILD_TYPE=${{matrix.target}} \
            -DCMAKE_CXX_COMPILER=${{matrix.compiler}} \
            -DCMAKE_CXX_STANDARD=${{matrix.cxx-version}}
           make -j
  build-macos:
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        compiler: [g++-12, clang++]
        c_compiler: [g++-12, clang++]
        cxx_version: [17, 20]
        target: [Debug, Release]
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
           mkdir -p build
           cd build
           cmake .. \
            -DCMAKE_BUILD_TYPE=${{matrix.target}} \
            -DCMAKE_CXX_COMPILER=${{matrix.compiler}} \
            -DCMAKE_CXX_STANDARD=${{matrix.cxx_version}}
           make -j
  build-windows:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        compiler: [cl, clang++]
        cxx-version: [17, 20]
        target: [Debug, Release]
    steps:
    - uses: actions/checkout@v2
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.10.0
    - name: build
      run: |
           mkdir -p build
           cd build
           cmake .. `
            -DCMAKE_BUILD_TYPE=${{matrix.target}} `
            -DCMAKE_CXX_COMPILER=${{matrix.compiler}} `
            -DCMAKE_CXX_STANDARD=${{matrix.cxx_version}} `
           msbuild .\libassert.sln
  build-mingw:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        compiler: [g++]
        target: [Debug, Release]
    steps:
    - uses: actions/checkout@v2
    - name: Enable Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1.10.0
    - name: build
      run: |
           mkdir -p build
           cd build
           cmake .. `
            -DCMAKE_BUILD_TYPE=${{matrix.target}} `
            -DCMAKE_CXX_COMPILER=${{matrix.compiler}} `
            -DCMAKE_CXX_STANDARD=${{matrix.cxx_version}} `
            "-GUnix Makefiles"
           make -j
