name: clang-tidy

on:
  push:
  pull_request:

jobs:
  clang-tidy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: |
           sudo apt install clang-tidy
           wget https://raw.githubusercontent.com/jeremy-rifkin/cpptrace/master/include/cpptrace/cpptrace.hpp
           mkdir include/cpptrace
           mv -v cpptrace.hpp include/cpptrace
           mkdir include/assert
           cp -v include/assert.hpp include/assert
    - name: clang-tidy
      run: |
           chmod +x lint.sh && ./lint.sh
