name: lint

on:
  push:
  pull_request:

jobs:
  clang-tidy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: |
           sudo apt install clang-tidy
           mkdir build
           cd build
           cmake .. -DCMAKE_BUILD_TYPE=Debug
    - name: clang-tidy
      run: |
           chmod +x lint.sh
           ./lint.sh
